HandyCanNode: include/HandyCAN.h File Reference
HandyCAN.h File Reference
HandyCAN node library.
#include "stm32f10x_conf.h"
Data Structures
struct HandyCAN_package
local state and configuration info
Macros
#define HC_VERSION 1
The current version of handycan.
#define HC_DEST_MASK 0x1F
Destination address mask.
#define HC_SRC_MASK 0x3E0
Source address mask.
#define HC_SRC_OFFSET 5
Source address offset.
#define HC_RESERVED_BIT 0x400
Reserved ID bit.
#define HC_RESERVED_BIT_OFFSET 10
Reserved ID bit offset.
#define HC_BROADCAST_ADDR 0x1F
HandyCAN broadcast address.
#define HC_CAN_SEND_TIMEOUT 0xFFFFF
CAN transmit timeout (unused at the moment)
#define HC_KEEP_STATISTICS 1
If this is set to 1, statistsics are kept.
Functions
int8_t HandyCAN_init (CAN_TypeDef *CANx, uint8_t local_addr, uint8_t CAN_Mode, IRQn_Type FIFO0_IRQ, IRQn_Type FIFO1_IRQ)
Initializes handyCAN to a specific CAN peripheral.
int8_t HandyCAN_transmit (uint8_t destination, uint8_t *data, uint8_t len)
int8_t HandyCAN_recievePackage (uint8_t FIFONumber, struct HandyCAN_package *package)
Takes a CAN Message and translates it into a HandyCAN packet.
int8_t HandyCAN_remainingMailboxes (void)
Check how many mailboxes there are available.
int8_t HandyCAN_isTransmitting (void)
Check if there are packets currently being transmitted.
uint64_t HandyCAN_sentPackets (void)
returns the amount of packages sent since init
uint64_t HandyCAN_recievedPackets (void)
returns the amount of packages received since init
uint64_t HandyCAN_failCount (void)
returns the failures since init
void HandyCAN_dumpRxPackage (struct HandyCAN_package *package)
For debug. Dumps a received HandyCAN Packet to STDOUT.
void HandyCAN_dumpCanRxMessage (CanRxMsg *rx_msg)
For debug. Dumps a received can message to STDOUT.
Detailed Description
HandyCAN node library.
Author
SirVolta
Date
Sep 18, 2017
Note
Function descriptions are in source file
Definition in file HandyCAN.h.
Macro Definition Documentation
HC_BROADCAST_ADDR
#define HC_BROADCAST_ADDR 0x1F
HandyCAN broadcast address.
Definition at line 47 of file HandyCAN.h.
Referenced by HandyCAN_dumpRxPackage(), HandyCAN_init(), and main().
HC_CAN_SEND_TIMEOUT
#define HC_CAN_SEND_TIMEOUT 0xFFFFF
CAN transmit timeout (unused at the moment)
Definition at line 50 of file HandyCAN.h.
HC_DEST_MASK
#define HC_DEST_MASK 0x1F
Destination address mask.
Definition at line 34 of file HandyCAN.h.
Referenced by HandyCAN_recievePackage().
HC_KEEP_STATISTICS
#define HC_KEEP_STATISTICS 1
If this is set to 1, statistsics are kept.
Definition at line 53 of file HandyCAN.h.
HC_RESERVED_BIT
#define HC_RESERVED_BIT 0x400
Reserved ID bit.
Definition at line 42 of file HandyCAN.h.
HC_RESERVED_BIT_OFFSET
#define HC_RESERVED_BIT_OFFSET 10
Reserved ID bit offset.
Definition at line 44 of file HandyCAN.h.
HC_SRC_MASK
#define HC_SRC_MASK 0x3E0
Source address mask.
Definition at line 37 of file HandyCAN.h.
Referenced by HandyCAN_recievePackage().
HC_SRC_OFFSET
#define HC_SRC_OFFSET 5
Source address offset.
Definition at line 39 of file HandyCAN.h.
Referenced by HandyCAN_recievePackage(), and HandyCAN_transmit().
HC_VERSION
#define HC_VERSION 1
The current version of handycan.
Definition at line 31 of file HandyCAN.h.
Function Documentation
HandyCAN_dumpCanRxMessage()
void HandyCAN_dumpCanRxMessage (CanRxMsg * rx_msg)
For debug. Dumps a received can message to STDOUT.
Parameters
[in] rx_msg incoming can message to dump
Definition at line 423 of file HandyCAN.c.
 {
   trace_printf("StdId: %#x\n"
            "ExtID: %#x\n"
            "IDE: %#x\n"
            "RTR: %#x\n"
            "DLC: %u\n"
            "FMI: %#x\n",
            rx_msg->StdId, rx_msg->ExtId, rx_msg->IDE, rx_msg->RTR,
            rx_msg->DLC, rx_msg->FMI);
   for (uint8_t i = 0; i < 8; i++)
     trace_printf("Data[%u]: %#x %u\n", i, rx_msg->Data[i], rx_msg->Data[i]);
 }
HandyCAN_dumpRxPackage()
void HandyCAN_dumpRxPackage (struct HandyCAN_package * package)
For debug. Dumps a received HandyCAN Packet to STDOUT.
Parameters
[in] package incoming handyCAN package to dump
Definition at line 401 of file HandyCAN.c.
References HandyCAN_package::data, HandyCAN_package::dest_adress, HC_BROADCAST_ADDR, HandyCAN_package::len, and HandyCAN_package::source_adress.
Referenced by CAN1_RX1_IRQHandler(), and USB_LP_CAN1_RX0_IRQHandler().
 {
   if (package->dest_adress == HC_BROADCAST_ADDR)
     {
       trace_printf("Incoming BROADCAST from %#x with intent: %u\n",
            package->source_adress, package->data[0]);
     }
   else
     {
       trace_printf("Received message from %#x with intent: %u\n",
            package->source_adress, package->data[0]);
     }
   for (uint8_t i = 1; i < package->len; i++)
     trace_printf("Data[%u]: %#x %u\n", i, package->data[i], package->data[i]);
 }
HandyCAN_failCount()
uint64_t HandyCAN_failCount (void)
returns the failures since init
Note
returns 0 if statistics are disabled. Set HC_KEEP_STATISTICS to 1 if required
Returns
amount of failures, 0 if disabled
Definition at line 387 of file HandyCAN.c.
References handycan.
 {
 #if HC_KEEP_STATISTICS
   return handycan.failures;
 #else
   return 0;
 #endif
 }
HandyCAN_init()
int8_t HandyCAN_init (CAN_TypeDef * CANx, uint8_t local_addr, uint8_t CAN_Mode, IRQn_Type FIFO0_IRQ, IRQn_Type FIFO1_IRQ)
Initializes handyCAN to a specific CAN peripheral.
Parameters
[in,out] CANx the can peripheral to use
[in] local_addr the address of this node
[in] CAN_Mode mode to initialize the CAN peripheral into
[in] FIFO0_IRQ interrupt channel of own address FIFO.
[in] FIFO1_IRQ interrupt channel of broadcast FIFO.
Note
Takes over full access of the CAN peripheral. GPIO setup is to be done in user application. If using CAN2, change the interrupt function names accordingly.
Returns
0: ok,
Todo:
Error handling, check can init
Definition at line 70 of file HandyCAN.c.
References assert_param, HandyCAN_config::CANx, handycan, HC_BROADCAST_ADDR, and HandyCAN_config::local_address.
Referenced by main().
 {
   CAN_InitTypeDef CAN_InitStruct;
   NVIC_InitTypeDef NVIC_InitStruct;
   CAN_FilterInitTypeDef CAN_FilterInitStruct;
   assert_param(IS_CAN_ALL_PERIPH(CANx));
   //Address must be in between 0x01 and 0x1E (1 and 30), 29 possible.
   assert_param(local_addr < 0x1F);
   assert_param(local_addr != 0x1F);
   assert_param(local_addr != 0x00);
   assert_param(IS_CAN_MODE(CAN_Mode));
   handycan.CANx = CANx;
   handycan.local_address = local_addr;
 #if HC_KEEP_STATISTICS
   handycan.tx_packets = 0;
   handycan.rx_packets = 0;
   handycan.failures = 0;
 #endif
   //Configure the CAN
   CAN_DeInit(handycan.CANx);
   CAN_StructInit(&CAN_InitStruct);
   CAN_InitStruct.CAN_TTCM = DISABLE;
   CAN_InitStruct.CAN_ABOM = DISABLE;
   CAN_InitStruct.CAN_AWUM = DISABLE;
   CAN_InitStruct.CAN_NART = DISABLE;
   CAN_InitStruct.CAN_RFLM = DISABLE;
   CAN_InitStruct.CAN_TXFP = DISABLE;
   CAN_InitStruct.CAN_Mode = CAN_Mode;
   CAN_InitStruct.CAN_SJW = CAN_SJW_1tq;
   CAN_InitStruct.CAN_BS1 = CAN_BS1_3tq;
   CAN_InitStruct.CAN_BS2 = CAN_BS2_5tq;
   CAN_InitStruct.CAN_Prescaler = 4; //4: 1M, 8: 500k
   CAN_Init(handycan.CANx, &CAN_InitStruct);
   // Set the filter to receive everything addressed to us into FIFO0
   CAN_FilterInitStruct.CAN_FilterNumber = 0;
   CAN_FilterInitStruct.CAN_FilterMode = CAN_FilterMode_IdMask;
   CAN_FilterInitStruct.CAN_FilterScale = CAN_FilterScale_32bit;
   // match our address into bits 0..4 of the 11 id bits
   // shift 5 to the left, as this is a 32bit register
   CAN_FilterInitStruct.CAN_FilterIdHigh = handycan.local_address << 5;
   CAN_FilterInitStruct.CAN_FilterIdLow = 0;
   // only look at bit 0..4 of the id bits
   CAN_FilterInitStruct.CAN_FilterMaskIdHigh = 0x1F << 5;
   CAN_FilterInitStruct.CAN_FilterMaskIdLow = 0x0000;
   CAN_FilterInitStruct.CAN_FilterFIFOAssignment = 0;
   CAN_FilterInitStruct.CAN_FilterActivation = ENABLE;
   CAN_FilterInit(&CAN_FilterInitStruct);
   // Set the filter to receive broadcast into FIFO1
   CAN_FilterInitStruct.CAN_FilterNumber = 1;
   CAN_FilterInitStruct.CAN_FilterMode = CAN_FilterMode_IdMask;
   CAN_FilterInitStruct.CAN_FilterScale = CAN_FilterScale_32bit;
   // match broadcast address in bits 0..4 of the id bits
   // shift 5 to the left as it is a 32 bit register
   CAN_FilterInitStruct.CAN_FilterIdHigh = HC_BROADCAST_ADDR << 5; // broadcast address
   CAN_FilterInitStruct.CAN_FilterIdLow = 0;
   // match only bit 0 to 4 in the id section
   CAN_FilterInitStruct.CAN_FilterMaskIdHigh = 0x1F << 5;
   CAN_FilterInitStruct.CAN_FilterMaskIdLow = 0x0000;
   CAN_FilterInitStruct.CAN_FilterFIFOAssignment = 1;
   CAN_FilterInitStruct.CAN_FilterActivation = ENABLE;
   CAN_FilterInit(&CAN_FilterInitStruct);
   //Setup receive interrupt for FIFO0(own address) data
   NVIC_InitStruct.NVIC_IRQChannel = FIFO0_IRQ;
   NVIC_InitStruct.NVIC_IRQChannelPreemptionPriority = 0;
   NVIC_InitStruct.NVIC_IRQChannelSubPriority = 0;
   NVIC_InitStruct.NVIC_IRQChannelCmd = ENABLE;
   NVIC_Init(&NVIC_InitStruct);
   CAN_ITConfig(handycan.CANx, CAN_IT_FMP0, ENABLE);
   NVIC_EnableIRQ(FIFO0_IRQ);
   //Setup for FIFO1(broadcast) data
   NVIC_InitStruct.NVIC_IRQChannel = FIFO1_IRQ;
   NVIC_InitStruct.NVIC_IRQChannelPreemptionPriority = 0;
   NVIC_InitStruct.NVIC_IRQChannelSubPriority = 0;
   NVIC_InitStruct.NVIC_IRQChannelCmd = ENABLE;
   NVIC_Init(&NVIC_InitStruct);
   CAN_ITConfig(handycan.CANx, CAN_IT_FMP1, ENABLE);
   NVIC_EnableIRQ(FIFO1_IRQ);
   return 0;
 }
HandyCAN_isTransmitting()
int8_t HandyCAN_isTransmitting (void)
Check if there are packets currently being transmitted.
Note
checks if there is a mailbox in use
Returns
1: transmit packet queued. 0: idle.
Definition at line 343 of file HandyCAN.c.
References HandyCAN_remainingMailboxes().
 {
   if (HandyCAN_remainingMailboxes() < 3)
     return 1;
   else
     return 0;
 }
HandyCAN_recievedPackets()
uint64_t HandyCAN_recievedPackets (void)
returns the amount of packages received since init
Note
returns 0 if statistics are disabled. Set HC_KEEP_STATISTICS to 1 if required
Returns
amount of packages received, 0 if disabled
Definition at line 372 of file HandyCAN.c.
References handycan.
 {
 #if HC_KEEP_STATISTICS
   return handycan.rx_packets;
 #else
   return 0;
 #endif
 }
HandyCAN_recievePackage()
int8_t HandyCAN_recievePackage (uint8_t FIFONumber, struct HandyCAN_package * package) inline
Takes a CAN Message and translates it into a HandyCAN packet.
Parameters
[in] FIFONumber Which FIFO to read
[out] package output HandyCAN package
Note
Parts taken from MCD library
Returns
0: ok, -1 error, -2 non handyCAN message
Todo:
Error handling, improve reading data from RDxR register
HandyCAN only uses the standard ID.
Definition at line 169 of file HandyCAN.c.
References assert_param, HandyCAN_config::CANx, HandyCAN_package::data, HandyCAN_package::dest_adress, handycan, HC_DEST_MASK, HC_SRC_MASK, HC_SRC_OFFSET, HandyCAN_package::len, and HandyCAN_package::source_adress.
Referenced by CAN1_RX1_IRQHandler(), and USB_LP_CAN1_RX0_IRQHandler().
 {
   // The standard identifier. This is between 0 and 0x7FF and will contain addressing data
   uint32_t StdId;
   // The type of identifier for the message being received.
   // HandyCAN only uses the standard ID
   uint8_t IDE;
   //Type of frame for the recieved message, CAN_remote_transmission_request
   //uint8_t RTR;
   //The index of the filter that was used to match this message. Can be 0 to 0xFF
   //uint8_t FMI;
   assert_param(IS_CAN_FIFO(FIFONumber));
   IDE = (uint8_t) 0x04 & handycan.CANx->sFIFOMailBox[FIFONumber].RIR;
   if (IDE != CAN_Id_Standard)
     {
 #if HC_KEEP_STATISTICS
       handycan.failures++;
 #endif
       return -2;
     }
   StdId = (uint32_t) 0x000007FF
       & (handycan.CANx->sFIFOMailBox[FIFONumber].RIR >> 21);
   //These are not used at the moment
   //FMI = (uint8_t) 0xFF & (handycan.CANx->sFIFOMailBox[FIFONumber].RDTR >> 8);
   //RTR = (uint8_t) 0x02 & handycan.CANx->sFIFOMailBox[FIFONumber].RIR;
   //Get the package data length
   package->len = (uint8_t) 0x0F & handycan.CANx->sFIFOMailBox[FIFONumber].RDTR;
   //Retrieve the data. TODO: optimize this.
   package->data[0] = (uint8_t) 0xFF
       & handycan.CANx->sFIFOMailBox[FIFONumber].RDLR;
   package->data[1] = (uint8_t) 0xFF
       & (handycan.CANx->sFIFOMailBox[FIFONumber].RDLR >> 8);
   package->data[2] = (uint8_t) 0xFF
       & (handycan.CANx->sFIFOMailBox[FIFONumber].RDLR >> 16);
   package->data[3] = (uint8_t) 0xFF
       & (handycan.CANx->sFIFOMailBox[FIFONumber].RDLR >> 24);
   package->data[4] = (uint8_t) 0xFF
       & handycan.CANx->sFIFOMailBox[FIFONumber].RDHR;
   package->data[5] = (uint8_t) 0xFF
       & (handycan.CANx->sFIFOMailBox[FIFONumber].RDHR >> 8);
   package->data[6] = (uint8_t) 0xFF
       & (handycan.CANx->sFIFOMailBox[FIFONumber].RDHR >> 16);
   package->data[7] = (uint8_t) 0xFF
       & (handycan.CANx->sFIFOMailBox[FIFONumber].RDHR >> 24);
   //Release the FIFO mailbox
   if (FIFONumber == CAN_FIFO0)
     handycan.CANx->RF0R |= CAN_RF0R_RFOM0;
   else
     handycan.CANx->RF1R |= CAN_RF1R_RFOM1;
   // Decode the addresses
   // Again STDID first 5 bits destination address, then 5 bits source addr, then 1 reserved
   package->source_adress = (StdId & HC_SRC_MASK) >> HC_SRC_OFFSET;
   package->dest_adress = StdId & HC_DEST_MASK;
 #if HC_KEEP_STATISTICS
   handycan.rx_packets++;
 #endif
   return 0;
 }
HandyCAN_remainingMailboxes()
int8_t HandyCAN_remainingMailboxes (void)
Check how many mailboxes there are available.
Note
Tests if it is possible to transmit
Returns
0: no, 1, one remaining, 2: 2 remaining, 3: 3 remaining
Definition at line 244 of file HandyCAN.c.
References HandyCAN_config::CANx, and handycan.
Referenced by HandyCAN_isTransmitting(), and main().
 {
   uint8_t transmit_mailbox_remaining;
   if ((handycan.CANx->TSR & CAN_TSR_TME0) == CAN_TSR_TME0)
     transmit_mailbox_remaining = 3;
   else if ((handycan.CANx->TSR & CAN_TSR_TME1) == CAN_TSR_TME1)
     transmit_mailbox_remaining = 2;
   else if ((handycan.CANx->TSR & CAN_TSR_TME2) == CAN_TSR_TME2)
     transmit_mailbox_remaining = 1;
   else
     transmit_mailbox_remaining = 0;
   return transmit_mailbox_remaining;
 }
HandyCAN_sentPackets()
uint64_t HandyCAN_sentPackets (void)
returns the amount of packages sent since init
Note
returns 0 if statistics are disabled. Set HC_KEEP_STATISTICS to 1 if required
Returns
amount of packages sent, 0 if disabled
Definition at line 357 of file HandyCAN.c.
References handycan.
 {
 #if HC_KEEP_STATISTICS
   return handycan.tx_packets;
 #else
   return 0;
 #endif
 }
HandyCAN_transmit()
int8_t HandyCAN_transmit (uint8_t destination, uint8_t * data, uint8_t len)