HandyCanNode: src/main.c File Reference
main.c File Reference
HandyCAN node library test.
#include "stm32f10x_conf.h"
#include "svlib_stm32f10x.h"
#include "HandyCAN.h"
Macros
#define INTENT_NODE_UPTIME 111
Functions
void USB_LP_CAN1_RX0_IRQHandler (void)
Called when package addressed to us is received.
void CAN1_RX1_IRQHandler (void)
Called when broadcast package is received.
void SysTick_Handler (void)
int main (void)
Variables
uint64_t systick_ms = 0
Detailed Description
HandyCAN node library test.
Author
SirVolta
Date
Sep 18, 2017
Note
Test and basic loopback demo of HandyCAN
Definition in file main.c.
Macro Definition Documentation
INTENT_NODE_UPTIME
#define INTENT_NODE_UPTIME 111
Definition at line 54 of file main.c.
Referenced by main().
Function Documentation
CAN1_RX1_IRQHandler()
void CAN1_RX1_IRQHandler (void)
Called when broadcast package is received.
Note
needs changing if peripheral is not CAN1
Definition at line 78 of file main.c.
References HandyCAN_dumpRxPackage(), and HandyCAN_recievePackage().
 {
   struct HandyCAN_package package;
   trace_puts("BCast");
   HandyCAN_recievePackage(CAN_FIFO1, &package);
   HandyCAN_dumpRxPackage(&package);
 }
main()
int main (void)
Place the system uptime in the data bytes as a example
Place the system uptime in the data bytes as a example
There should be 3 mailboxes avaliable
Transmit data to ourself, then increment the counter, And broadcast everything but the days.
Definition at line 94 of file main.c.
References HandyCAN_package::data, delayUs(), HandyCAN_init(), HandyCAN_remainingMailboxes(), HandyCAN_transmit(), HC_BROADCAST_ADDR, time_types::hours, initDWT(), INTENT_NODE_UPTIME, time_types::minutes, time_types::seconds, secondsToTime(), and systick_ms.
 {
   GPIO_InitTypeDef GPIO_InitStruct;
   uint8_t data[8];
   struct time_types uptime;
   RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOA, ENABLE);
   RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOB, ENABLE);
   RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOC, ENABLE);
   RCC_APB2PeriphClockCmd(RCC_APB2Periph_AFIO, ENABLE);
   RCC_APB1PeriphClockCmd(RCC_APB1Periph_CAN1, ENABLE);
   // Configure CAN pin: A11: RX
   GPIO_InitStruct.GPIO_Pin = GPIO_Pin_11;
   GPIO_InitStruct.GPIO_Mode = GPIO_Mode_IPU;
   GPIO_InitStruct.GPIO_Speed = GPIO_Speed_50MHz;
   GPIO_Init(GPIOA, &GPIO_InitStruct);
   // Configure CAN pin: A12: TX
   GPIO_InitStruct.GPIO_Pin = GPIO_Pin_12;
   GPIO_InitStruct.GPIO_Mode = GPIO_Mode_AF_OD;
   GPIO_InitStruct.GPIO_Speed = GPIO_Speed_50MHz;
   GPIO_Init(GPIOA, &GPIO_InitStruct);
   // onboard led
   GPIO_InitStruct.GPIO_Pin = GPIO_Pin_13;
   GPIO_InitStruct.GPIO_Mode = GPIO_Mode_Out_OD;
   GPIO_InitStruct.GPIO_Speed = GPIO_Speed_50MHz;
   GPIO_Init(GPIOC, &GPIO_InitStruct);
   //SysTick timer
   SysTick_CLKSourceConfig(SysTick_CLKSource_HCLK);
   SysTick_Config(SystemCoreClock / 1000);
   SystemCoreClockUpdate();
   systick_ms = 0;
   initDWT();
   //Init handycan: CAN1, our address is 0x0F, loopback mode for testing, CAN1 interrupts.
   HandyCAN_init(CAN1, 0x0A, CAN_Mode_Normal, USB_LP_CAN1_RX0_IRQn,
         CAN1_RX1_IRQn);
   // test data
   data[5] = 0;   // counter byte
   trace_puts("HandyCAN Ready");
   while (1)
     {
       while (HandyCAN_remainingMailboxes())
     {
       uptime.seconds = (uint32_t) (systick_ms / 1000);
       secondsToTime(&uptime);
       data[0] = INTENT_NODE_UPTIME;
       data[1] = uptime.seconds;
       data[2] = uptime.minutes;
       data[3] = uptime.hours;
       data[4]++;
       data[5] = 0xE0;
       data[6] = 0xEF;
       HandyCAN_transmit(0x0A, data, 7);
     }
     }
   while (1)
     {
       uptime.seconds = (uint32_t) (systick_ms / 1000);
       secondsToTime(&uptime);
       data[0] = INTENT_NODE_UPTIME;
       data[1] = uptime.seconds;
       data[2] = uptime.minutes;
       data[3] = uptime.hours;
       data[4]++;
       data[5] = 0xE0;
       data[6] = 0xEF;
       trace_printf("Available: %u\n", HandyCAN_remainingMailboxes());
       HandyCAN_transmit(0x0A, data, 7);
       delayUs(2500 * 1000);
       uptime.seconds = (uint32_t) (systick_ms / 1000);
       secondsToTime(&uptime);
       data[0] = INTENT_NODE_UPTIME;
       data[1] = uptime.seconds;
       data[2] = uptime.minutes;
       data[3] = uptime.hours;
       data[4]++;
       data[5] = 0xF0;
       data[6] = 0xFA;
       HandyCAN_transmit(HC_BROADCAST_ADDR, data, 7);
       trace_printf("Available: %u\n", HandyCAN_remainingMailboxes());
       delayUs(2500 * 1000);
     }
 }
SysTick_Handler()
void SysTick_Handler (void)
Definition at line 88 of file main.c.
References systick_ms.
 {
   systick_ms++;
 }
USB_LP_CAN1_RX0_IRQHandler()
void USB_LP_CAN1_RX0_IRQHandler (void)
Called when package addressed to us is received.
Note
needs changing if peripheral is not CAN1
Definition at line 63 of file main.c.
References HandyCAN_package::data, and HandyCAN_recievePackage().
 {
   struct HandyCAN_package package;
   HandyCAN_recievePackage(CAN_FIFO0, &package);
   //HandyCAN_dumpRxPackage(&package);
   if (package.data[0] == 2)
     GPIO_WriteBit(GPIOC, GPIO_Pin_13, package.data[1]);
 }
Variable Documentation
systick_ms
uint64_t systick_ms = 0
Definition at line 56 of file main.c.
Referenced by main(), and SysTick_Handler().