HandyCanNode: include/svlib_stm32f10x.h File Reference
svlib_stm32f10x.h File Reference
SirVolta's library.
#include <stdint.h>
#include "stm32f10x_conf.h"
#include "diag/Trace.h"
Data Structures
struct time_types
Macros
#define DWT_CYCLES DWT->CYCCNT
DWT clock cycles. Useful for timing execution.
#define GPIO_ToggleBits(GPIOx, GPIO_Pin) GPIO_WriteBit(GPIOx, GPIO_Pin, !GPIO_ReadOutputDataBit(GPIOx, GPIO_Pin));
#define delayMs(ms) delayUs (ms * 1000);
#define print_size(str, object) trace_printf("%s: %i bytes %i bits\n", str, sizeof(object), sizeof(object) * 8)
Functions
void secondsToTime (struct time_types *tim)
converts seconds to days, hours, minutes and seconds
void initDWT (void)
Initializes Data Watchpoint and Trace Registers (DWT) processor cycle counter. Usually, this is already done by uOS clock init and is not required.
void delayUs (uint32_t us)
Holds up execution by n microseconds to maximum 52 seconds. Reqiures DWT to be initialized.
Detailed Description
SirVolta's library.
Author
SirVolta Emacs
Date
Mar 1, 2016
Note
Function descriptions are in source file
Definition in file svlib_stm32f10x.h.
Macro Definition Documentation
delayMs
#define delayMs (ms) delayUs (ms * 1000);
Definition at line 50 of file svlib_stm32f10x.h.
DWT_CYCLES
#define DWT_CYCLES DWT->CYCCNT
DWT clock cycles. Useful for timing execution.
timer Example
uint32_t start, end;
// DWT_CYCLES = 0; // use if you worried about overflow during measurement
...
start = DWT_CYCLES;
// code to be measured
end = DWT_CYCLES;
trace_printf("%d ms\r\n",((end-start)/72000)); // at 72MHz
Definition at line 47 of file svlib_stm32f10x.h.
Referenced by delayUs().
GPIO_ToggleBits
#define GPIO_ToggleBits (GPIOx, GPIO_Pin) GPIO_WriteBit(GPIOx, GPIO_Pin, !GPIO_ReadOutputDataBit(GPIOx, GPIO_Pin));
Definition at line 49 of file svlib_stm32f10x.h.
Referenced by USB_LP_CAN1_RX0_IRQHandler().
print_size
#define print_size (str, object) trace_printf("%s: %i bytes %i bits\n", str, sizeof(object), sizeof(object) * 8)
Definition at line 51 of file svlib_stm32f10x.h.
Function Documentation
delayUs()
void delayUs (uint32_t us)
Holds up execution by n microseconds to maximum 52 seconds. Reqiures DWT to be initialized.
Parameters
[in] us Microseconds to stall execution
Definition at line 81 of file svlib_stm32f10x.c.
References assert_param, and DWT_CYCLES.
Referenced by main().
 {
  int32_t tp = DWT_CYCLES + us * (SystemCoreClock / 1000000);
  tp += 2;
  assert_param (us < (52000000)); // max 52 second delay, check after storing initial cycle count
  while (((int32_t) DWT_CYCLES - tp) < 0)
   ;
 }
initDWT()
void initDWT (void)
Initializes Data Watchpoint and Trace Registers (DWT) processor cycle counter. Usually, this is already done by uOS clock init and is not required.
Definition at line 67 of file svlib_stm32f10x.c.
Referenced by main().
 {
    CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk;
    DWT->CYCCNT = 0;
    DWT->CTRL |= DWT_CTRL_CYCCNTENA_Msk;
 }
secondsToTime()
void secondsToTime (struct time_types * tim)
converts seconds to days, hours, minutes and seconds
Parameters
[in,out] tim time_types pointer with seconds initialized
Note
86400 is amount of seconds in one day
Definition at line 52 of file svlib_stm32f10x.c.
References time_types::days, time_types::hours, time_types::minutes, and time_types::seconds.
Referenced by main().
 {
  tim->days = (uint32_t)(tim->seconds / 86400);
  tim->seconds -= tim->days * 86400;
  tim->hours = (uint32_t)(tim->seconds / 3600);
  tim->seconds -= tim->hours * 3600;
  tim->minutes = (uint32_t)(tim->seconds / 60);
  tim->seconds -= tim->minutes * 60;
 }